import { Geist, Geist_Mono, Poppins, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/foundations/navbar";
import Footer from "@/components/ui/foundations/footer";
// import { SidebarProvider, SidebarTrigger  } from "@/components/ui/shadcn/sidebar"
// import AppSidebar from "@/components/ui/foundations/app-sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
  subsets: ["latin"]
});

const open_sans = Open_Sans ({
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-opensans",
  display: "swap",
  subsets: ["latin"]
})


export const metadata = {
  title: "Arino Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${open_sans.className} antialiased bg-[#181818]`}
      
      >
        <Navbar/>
         
        {children}
        <Footer />
      </body>
    </html>
  );
}
